name: 'auto-release-action'
description: 'Auto release action'
inputs:
  github-token:
    description: 'Token to access github'
    required: true
  dry-run:
    description: Create changelog but don't create a release
    required: false
    default: "false"
  prev-version-name:
    description: 'Starting point for changes, defaults to env.PREV_VERSION_NAME'
    required: false
    default: 'env.PREV_VERSION_NAME'
  tag-prefix:
    description: 'Prefix used for target-version'
    required: false
    default: "v"
  target-version:
    description: 'The version to be release, defaults to env.AUTO_VERSION'
    required: false
    default: 'env.AUTO_VERSION'
outputs:
  release-notes:
    description: 'The generated release notes'
  release-id:
    description: 'Release id of the created release'
  upload-url:
    description: 'Upload url used for assets'
runs:
  using: 'node16'
  main: 'dist/index.js'
