const Changelog = require("./changelog");
const { Commit, Issue } = require("./git");

describe("changelog.js", () => {
  test("no issues", async () => {
    expect(
      new Changelog("2022-10-13", "v0.0.1", "v0.0.2", [
        new Commit("user", "message"),
      ]).asString()
    ).toContain("No notable improvements");
  });
  test("commits when no previous version", async () => {
    expect(
      new Changelog("2022-10-13", undefined, "v0.0.1", [], []).asString()
    ).toContain("/commits/v0.0.1");
  });
  test("compare when previous version", async () => {
    expect(
      new Changelog("2022-10-13", "v0.0.0", "v0.0.1", [], []).asString()
    ).toContain("/compare/v0.0.0...v0.0.1");
  });
  test("Complete example", async () => {
    expect(
      new Changelog(
        "2022-10-13",
        "v0.0.0",
        "v0.0.01",
        [new Commit("one", "fixes #1"), new Commit("two", "fixes #2")],
        [
          new Issue(
            "1",
            "http://github.com/owner/repo/issues/1",
            "Fixed the first issue"
          ),
          new Issue(
            "2",
            "http://github.com/owner/repo/issues/2",
            "Fixed the second issue"
          ),
        ]
      ).asString()
    ).toBe(
      "<sup><sup>*Changelog generated by [auto-release-action](https://github.com/npetzall/auto-release-action)*</sup></sup>\n" +
        "\n" +
        "#### v0.0.01\n" +
        " - 2022-10-13 - [2 commit(s)](https://github.com/owner/repo/compare/v0.0.0...v0.0.01) by one, two\n" +
        " - Fixed the first issue [(#1)](http://github.com/owner/repo/issues/1)\n" +
        " - Fixed the second issue [(#2)](http://github.com/owner/repo/issues/2)"
    );
  });
});
